apiVersion: v1
kind: Pod
metadata:
  name: resourcemgmt1
  labels:
   app: v1.0.0
spec:
  containers:
  - name: resourcemgmt1
    image: docker.io/polinux/stress:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "250Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
